### ISSUE TITLE
BUG: activate-deactivate cycle doesn't leave $PATH unchanged

### ISSUE THREAD

**Issue by andreas-h** [conda/conda-env#62]
After activating and de-activating a conda environment, my `$PATH` is not the same as before:

    $ echo $PATH
    /home2/hilboll/bin:/home2/hilboll/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    $ source pyenv/bin/activate ./pyenv/
    discarding /home2/hilboll/anaconda/bin from PATH
    prepending /home2/_home/hilboll/prj/2014_no2trends-india/pyenv/bin to PATH
    (/home2/hilboll/prj/2014_no2trends-india/pyenv) $ ~/prj/2014_no2trends-india $ echo $PATH
    /home2/_home/hilboll/prj/2014_no2trends-india/pyenv/bin:/home2/hilboll/bin:/home2/hilboll/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    (/home2/hilboll/prj/2014_no2trends-india/pyenv) $ ~/prj/2014_no2trends-india $ source pyenv/bin/deactivate
    discarding /home2/hilboll/prj/2014_no2trends-india/pyenv/bin from PATH
    $ echo $PATH
    /home2/hilboll/anaconda/bin:/home2/_home/hilboll/prj/2014_no2trends-india/pyenv/bin:/home2/hilboll/bin:/home2/hilboll/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

However, I would expect that no conda-related elements should be in my path whatsoever.

**Comment by tswicegood** [comment]
Thanks for the note @andreas-h.  This is definitely a bug, but one that doesn't actually surprise me.  The way `deactivate` was originally written was from a point-of-view where the conda root bin directory (`~/anaconda/bin`) is always on the PATH so it should be returned.

**Comment by malev** [comment]
@andreas-h I think this should be fixed by now:
```
☁  ~   echo $PATH
/Users/mvanetta/.rbenv/shims:/Users/mvanetta/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mvanetta/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin
☁  ~  source activate anaconda.org
discarding /Users/mvanetta/miniconda3/bin from PATH
prepending /Users/mvanetta/miniconda3/envs/anaconda.org/bin to PATH
(anaconda.org)☁  ~  source deactivate
discarding /Users/mvanetta/miniconda3/envs/anaconda.org/bin from PATH
☁  ~  echo $PATH
/Users/mvanetta/miniconda3/bin:/Users/mvanetta/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mvanetta/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin
☁  ~
```

**Comment by andreas-h** [comment]
the problem still exists.

It seems to work correctly if I already have `anaconda/bin` in my path and do `source activate -nmyenv`:

    echo $PATH
    /home2/hilboll/anaconda/bin:/home2/hilboll/bin:/home2/hilboll/scripts:/home2/hilboll/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home2/hilboll/.local/MRT/bin
    source activate py3
    discarding /home2/hilboll/anaconda/bin from PATH
    prepending /home2/hilboll/anaconda/envs/py3/bin to PATH
    source deactivate
    discarding /home2/hilboll/anaconda/envs/py3/bin from PATH
    echo $PATH
    /home2/hilboll/anaconda/bin:/home2/hilboll/bin:/home2/hilboll/scripts:/home2/hilboll/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home2/hilboll/.local/MRT/bin

However, when I do not have `anaconda/bin` on my `$PATH` and I do `source path/to/activate path/to/environment`, the problem is there:

    hilboll@shaula ~/prj/2015_vrs $ echo $PATH
    /home2/hilboll/bin:/home2/hilboll/scripts:/home2/hilboll/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home2/hilboll/.local/MRT/bin
    hilboll@shaula ~/prj/2015_vrs $ source ./pyenv/bin/activate ./pyenv/
    discarding /home2/hilboll/anaconda/bin from PATH
    prepending /home2/_home/hilboll/prj/2015_vrs/pyenv/bin to PATH
    (/home2/hilboll/prj/2015_vrs/pyenv)hilboll@shaula ~/prj/2015_vrs $ source ./pyenv/bin/deactivate 
    discarding /home2/hilboll/prj/2015_vrs/pyenv/bin from PATH
    hilboll@shaula ~/prj/2015_vrs $ echo $PATH
    /home2/hilboll/anaconda/bin:/home2/_home/hilboll/prj/2015_vrs/pyenv/bin:/home2/hilboll/bin:/home2/hilboll/scripts:/home2/hilboll/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home2/hilboll/.local/MRT/bin

And, yes, `activate` is a symlink to the most recent conda install:

    hilboll@shaula ~/prj/2015_vrs $ ls -lh pyenv/bin/activate 
    lrwxrwxrwx 1 hilboll users 36 Mär 25  2015 pyenv/bin/activate -> /home2/hilboll/anaconda/bin/activate
